"""initial migration

Revision ID: 4d27e8fe02e5
Revises: 94b4008a97b3
Create Date: 2025-12-08 19:04:09.211700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d27e8fe02e5'
down_revision: Union[str, None] = '94b4008a97b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Milestone',
    sa.Column('MilestoneID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.Column('ProjectID', sa.Integer(), nullable=True),
    sa.Column('ResponsibleEmpID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ProjectID'], ),
    sa.ForeignKeyConstraint(['ResponsibleEmpID'], ['Employee.EmpID'], ),
    sa.PrimaryKeyConstraint('MilestoneID')
    )
    op.create_index(op.f('ix_Milestone_MilestoneID'), 'Milestone', ['MilestoneID'], unique=False)
    op.alter_column('Building', 'YearBuilt',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_Building_BuildingCode'), 'Building', ['BuildingCode'], unique=False)
    op.create_index(op.f('ix_Department_DeptID'), 'Department', ['DeptID'], unique=False)
    op.create_index(op.f('ix_Division_DivisionID'), 'Division', ['DivisionID'], unique=False)
    op.create_index(op.f('ix_Employee_EmpID'), 'Employee', ['EmpID'], unique=False)
    op.create_foreign_key(None, 'Employee', 'Department', ['DeptID'], ['DeptID'])
    op.create_foreign_key(None, 'Employee', 'Division', ['DivisionID'], ['DivisionID'])
    op.alter_column('JobHistory', 'Title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('JobHistory', 'Salary',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False)
    op.create_index(op.f('ix_Phone_PhoneNumber'), 'Phone', ['PhoneNumber'], unique=False)
    op.create_index(op.f('ix_Project_ProjectID'), 'Project', ['ProjectID'], unique=False)
    op.alter_column('ProjectHistory', 'Role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ProjectHistory', 'Role',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('ix_Project_ProjectID'), table_name='Project')
    op.drop_index(op.f('ix_Phone_PhoneNumber'), table_name='Phone')
    op.alter_column('JobHistory', 'Salary',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True)
    op.alter_column('JobHistory', 'Title',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'Employee', type_='foreignkey')
    op.drop_constraint(None, 'Employee', type_='foreignkey')
    op.drop_index(op.f('ix_Employee_EmpID'), table_name='Employee')
    op.drop_index(op.f('ix_Division_DivisionID'), table_name='Division')
    op.drop_index(op.f('ix_Department_DeptID'), table_name='Department')
    op.drop_index(op.f('ix_Building_BuildingCode'), table_name='Building')
    op.alter_column('Building', 'YearBuilt',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_Milestone_MilestoneID'), table_name='Milestone')
    op.drop_table('Milestone')
    # ### end Alembic commands ###
