"""fix tax_reports table

Revision ID: 6c78bb125836
Revises: a4a816364b37
Create Date: 2025-12-08 19:57:11.319927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c78bb125836'
down_revision: Union[str, None] = 'a4a816364b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_reports',
    sa.Column('ReportID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.Column('FederalTax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('StateTax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('OtherTax', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['EmpID'], ['Employee.EmpID'], ),
    sa.PrimaryKeyConstraint('ReportID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_reports')
    # ### end Alembic commands ###
