"""initial schema with varchar lengths

Revision ID: 94b4008a97b3
Revises: 
Create Date: 2025-12-07 11:28:21.813615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b4008a97b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_index(op.f('ix_employees_emp_id'), 'employees', ['emp_id'], unique=False)
    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_history_id'), 'job_history', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_projects_project_id'), 'projects', ['project_id'], unique=False)
    op.create_table('milestones',
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('responsible_emp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['responsible_emp_id'], ['employees.emp_id'], ),
    sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_index(op.f('ix_milestones_milestone_id'), 'milestones', ['milestone_id'], unique=False)
    op.create_table('project_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.emp_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_history_id'), 'project_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_history_id'), table_name='project_history')
    op.drop_table('project_history')
    op.drop_index(op.f('ix_milestones_milestone_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_projects_project_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_job_history_id'), table_name='job_history')
    op.drop_table('job_history')
    op.drop_index(op.f('ix_employees_emp_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
